### ISSUE TITLE
npy文件在哪里下载

### ISSUE THREAD

**Issue by Marydsy** [yingsen1/UniMD#7]
在运行sh individual_train_ego4d_tad.sh命令的时候显示没有npy文件，报错如下
FileNotFoundError: [Errno 2] No such file or directory: './docker/TAD/Ego4d/feats/sorted_clip_feats/mq_videointern_verb/20b60cf7-067e-45e3-8885-c50ba13c6031.npy'
想问下从哪里可以下载npy文件

**Comment by yingsen1** [comment]
这里有链接可以下载：https://github.com/yingsen1/UniMD?tab=readme-ov-file#video-features
