### ISSUE TITLE
Could you provide another link for ActivityNet features ?

### ISSUE THREAD

**Issue by Yuuraa** [yingsen1/UniMD#8]
Hi,
Thank you for your great work!
I want to reproduce the result of your great work.
I wonder if you could share ActivityNet feature for localization, other than the Baidu link (I couldn't download the file..)

Thank you for your consideration!

**Comment by yingsen1** [comment]
i directly utilize the pre-extracted ActivityNet video feats provided by [this repo](https://github.com/OpenGVLab/InternVideo/tree/main/InternVideo1/Downstream/Temporal-Action-Localization) for InternVide backbone and [this repo](https://github.com/happyharrycn/actionformer_release?tab=readme-ov-file#to-reproduce-our-results-on-activitynet-13) for TSP backbone. Without permission, we do not have the authority to reproduce them on other storage platforms. However, I suggest contacting the author of InternVideo for other available alternatives.
